apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-ssikit
  labels:
    app: wallet-ssikit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallet-ssikit
  template:
    metadata:
      labels:
        app: wallet-ssikit
    spec:
      containers:
      - name: ssi-core-dev-env
        image: pablomarrtinez/wallet:v3.0.3
        command: ["/bin/sh", "-c"]
        args: 
          - |
            echo '127.0.0.1 umu-verifier umu-issuer umu-webWallet' >> /etc/hosts
            /app/ssikit.sh fullApi
            tail -f
        env:
        - name: ISSUER_PORT
          value: "32000"
        - name: VERIFIER_PORT
          value: "32001"
        - name: WALLET_PORT
          value: "32002"
        - name: PEER_ENDPOINT
          value: "192.168.49.1"
        - name: MODE
          value: "Default"
        - name: LOCAL
          value: "true"
        ports:
        - containerPort: 32000
        - containerPort: 32001
        - containerPort: 32002
        readinessProbe:
          httpGet:
            path: "/"  
            port: 32002
            scheme: HTTPS
          initialDelaySeconds: 15  
          periodSeconds: 5 
        volumeMounts:
        - name: shared-files
          mountPath: /app/src/main/kotlin/id/walt/services/ecosystems/fabric/resources/
      volumes:
      - name: shared-files
        hostPath:
          path: /mnt/shared
          type: Directory
